portes ouvertes
FablabLannion/FablabLannion.github.io pull request #112
Opened 2021-10-08 21:11 UTC by colvert

Signed-off-by: morgan Richomme <morganrichomme@mini-de-morgan-2.home>

2021-10-09 09:31 UTC, thierry7100 commented
OK pour moi

2021-10-09 11:12 UTC, FabTangi requested changes
2 petites fautes d'ortho je pense...

2021-10-09 11:12 UTC, FabTangi commented on _posts/2021-10-08-Portes ouvertes.md
> +Le fablab de Lannion est heureux d'annoncer ses premières portes ouvertes dans ses tous nouveaux locaux.
ses tout nouveau

2021-10-09 11:12 UTC, FabTangi commented on _posts/2021-10-08-Portes ouvertes.md
> +Le fablab de Lannion est heureux d'annoncer ses premières portes ouvertes dans ses tous nouveaux locaux.
ses tout nouveaux

2021-10-09 11:12 UTC, FabTangi commented on _posts/2021-10-08-Portes ouvertes.md
> +En attendant, après une année 2021 éprouvante marquée par une pandémie mondiale ayant entraînée un arrêt forcé de nos machines et de nos discussions passionées,
passionnées

2021-10-10 17:24 UTC, bernardarzur commented on _posts/2021-10-08-Portes ouvertes.md
> +En attendant, après une année 2021 éprouvante marquée par une pandémie mondiale ayant entraînée un arrêt forcé de nos machines et de nos discussions passionées,
passionnés

2021-10-10 17:25 UTC, bernardarzur commented on _posts/2021-10-08-Portes ouvertes.md
> +En attendant, après une année 2021 éprouvante marquée par une pandémie mondiale ayant entraînée un arrêt forcé de nos machines et de nos discussions passionées,
passionnées

2021-10-10 17:29 UTC, bernardarzur commented
OK pour moi

2021-10-10 19:18 UTC, merged