Creation 2023-09-20-programmation-octobre.md
FablabLannion/FablabLannion.github.io pull request #160
Opened 2023-09-15 15:15 UTC by KefeeDeMineor

2023-09-15 15:20 UTC, mcarti commented on _posts/2023-09-20-programmation-octobre.md
> +	<a href="{{ site.static_url }}/ProgFabLSept2023.png"><img src="{{ site.static_url }}/ProgFabLSept2023.png" alt="Affiche du programme de Septembre"></a>
c'est toujours l'image du planning d'octobre qui est affichée

2023-09-15 15:22 UTC, FabTangi requested changes

2023-09-15 15:22 UTC, FabTangi commented on _posts/2023-09-20-programmation-octobre.md
> +
Manque la date non?

2023-09-19 08:50 UTC, FabTangi requested changes

2023-09-19 08:50 UTC, FabTangi commented on _posts/2023-09-20-programmation-octobre.md
> +<h2>Horaires d'été</h2>
Serait-il possible de remplacer par le  nvx créneaux? 
De nouveaux créneaux les 1er et 3eme Samedi de chaque mois de 9H à 13H.
Le 7 Octobre, fermeture exceptionnelle, retrouvez nous à la Fête de la Science aux Ursulines, Lannion

2023-09-19 09:02 UTC, FabTangi approved these changes

2023-09-22 14:43 UTC, merged